### ISSUE TITLE
py-rrdtool?

### ISSUE THREAD

**Issue by ser** [ckhardin/collectd-graphene#1]
```
$ pip install py-rrdtool
Collecting py-rrdtool
  Could not find a version that satisfies the requirement py-rrdtool (from versions: )
No matching distribution found for py-rrdtool
```

this project looks dead indeed? https://pypi.org/project/py-rrdtool/

**Comment by ckhardin** [comment]
There were three packages that I am aware of

- rrdtool
- py-rrdtool
- python-rrdtool

So, it seems that the rrd tool was the original - and py-rrdtool is the result of compiling the "rrd tool" package and installing the python support from there and python-rrdtool is the PyPI package that is the most current.

In the embedded system we have, the py-rrdtool is what is installed from the buildroot rrd tool package and the setup.py ....

```
RRDTOOL_VERSION = 1.6.0
RRDTOOL_SITE = http://oss.oetiker.ch/rrdtool/pub
```

and then within the bindings and python

```
setup(name = "py-rrdtool",
      version = "0.2.2",
      description = "Python Interface to RRDTool",
```

So, I set the requirements up for embedded system and I guess the fix for this might to be another requirements for PyPI that uses the python-rrdtool package.

**Comment by ckhardin** [comment]
Updated to use "rrdtool" since that appears to be current package.
